export const rawTab1 = [
    {
        'Plan Details': 'Bronze Plan',
        'Interest Rate': '8.5%',
        'Investment Range': '$100 - $599',
        'Lock-in Period': '365',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Quarterly Bonus Plan',
        'Interest Rate': '9%',
        'Investment Range': '₹50,000 - ₹5,00,000',
        'Lock-in Period': '2 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Yearly Saver Plan',
        'Interest Rate': '10%',
        'Investment Range': '₹1,00,000 - ₹10,00,000',
        'Lock-in Period': '3 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'High Return Plan',
        'Interest Rate': '11%',
        'Investment Range': '₹5,00,000+',
        'Lock-in Period': '5 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Short-Term Booster',
        'Interest Rate': '7.5%',
        'Investment Range': '₹5,000 - ₹50,000',
        'Lock-in Period': '6 Months',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Elite Savings Plan',
        'Interest Rate': '9.5%',
        'Investment Range': '₹1,00,000 - ₹3,00,000',
        'Lock-in Period': '1 Year',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Silver Plan',
        'Interest Rate': '8%',
        'Investment Range': '₹50,000 - ₹2,00,000',
        'Lock-in Period': '2 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Green Growth Plan',
        'Interest Rate': '7.8%',
        'Investment Range': '₹10,000 - ₹1,00,000',
        'Lock-in Period': '1 Year',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Fast Track Plan',
        'Interest Rate': '6.5%',
        'Investment Range': '₹2,000 - ₹20,000',
        'Lock-in Period': '6 Months',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Family Protection Plan',
        'Interest Rate': '8.2%',
        'Investment Range': '₹50,000 - ₹3,00,000',
        'Lock-in Period': '3 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'High Growth Plan',
        'Interest Rate': '10.5%',
        'Investment Range': '₹1,00,000 - ₹5,00,000',
        'Lock-in Period': '4 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Quick Saver Plan',
        'Interest Rate': '7.2%',
        'Investment Range': '₹5,000 - ₹20,000',
        'Lock-in Period': '1 Year',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Capital Shield Plan',
        'Interest Rate': '7%',
        'Investment Range': '₹10,000 - ₹50,000',
        'Lock-in Period': '2 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Education Fund Plan',
        'Interest Rate': '9.7%',
        'Investment Range': '₹25,000 - ₹2,00,000',
        'Lock-in Period': '5 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Retirement Fund Plan',
        'Interest Rate': '8.5%',
        'Investment Range': '₹50,000 - ₹10,00,000',
        'Lock-in Period': '5 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Investment Builder Plan',
        'Interest Rate': '9%',
        'Investment Range': '₹1,00,000 - ₹7,00,000',
        'Lock-in Period': '3 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Starter Plan',
        'Interest Rate': '6.5%',
        'Investment Range': '₹2,000 - ₹10,000',
        'Lock-in Period': '1 Year',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Kuldeep Plan',
        'Interest Rate': '7.5%',
        'Investment Range': '₹50,000 - ₹1,00,000',
        'Lock-in Period': '2 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Gold Plan',
        'Interest Rate': '9.3%',
        'Investment Range': '₹1,00,000 - ₹5,00,000',
        'Lock-in Period': '4 Years',
        'Action': 'Invest',
    },
    {
        'Plan Details': 'Wealth Builder Plan',
        'Interest Rate': '8.8%',
        'Investment Range': '₹10,000 - ₹2,00,000',
        'Lock-in Period': '3 Years',
        'Action': 'Invest',
    },
];





export const rawTab2 = [
    {
        'Plan Details': 'Starter Plan',
        'Withdrawals': 'No Withdrawals',
        'Rewards Allocated': '₹200',
        'Accrued Rewards': '₹50',
        'Rewards Can Claim': '₹50',
        'Interest Rate': '6.5%',
        'Amount Invested': '₹2,000',
        'Days Remaining': '365',
        'Total Claims': '0',
    },
    {
        'Plan Details': 'Holiday Plan',
        'Withdrawals': '₹500',
        'Rewards Allocated': '₹400',
        'Accrued Rewards': '₹150',
        'Rewards Can Claim': '₹100',
        'Interest Rate': '7.5%',
        'Amount Invested': '₹10,000',
        'Days Remaining': '180',
        'Total Claims': '1',
    },
    {
        'Plan Details': 'Gold Plan',
        'Withdrawals': '₹1,000',
        'Rewards Allocated': '₹800',
        'Accrued Rewards': '₹300',
        'Rewards Can Claim': '₹200',
        'Interest Rate': '8.0%',
        'Amount Invested': '₹20,000',
        'Days Remaining': '250',
        'Total Claims': '2',
    },
    {
        'Plan Details': 'Wealth Builder Plan',
        'Withdrawals': '₹2,500',
        'Rewards Allocated': '₹1,500',
        'Accrued Rewards': '₹500',
        'Rewards Can Claim': '₹300',
        'Interest Rate': '9.5%',
        'Amount Invested': '₹50,000',
        'Days Remaining': '180',
        'Total Claims': '3',
    },
    {
        'Plan Details': 'Premium Plan',
        'Withdrawals': '₹5,000',
        'Rewards Allocated': '₹3,000',
        'Accrued Rewards': '₹1,200',
        'Rewards Can Claim': '₹800',
        'Interest Rate': '10.0%',
        'Amount Invested': '₹75,000',
        'Days Remaining': '450',
        'Total Claims': '4',
    },
    {
        'Plan Details': 'Elite Plan',
        'Withdrawals': '₹10,000',
        'Rewards Allocated': '₹5,000',
        'Accrued Rewards': '₹2,500',
        'Rewards Can Claim': '₹1,500',
        'Interest Rate': '12.0%',
        'Amount Invested': '₹1,00,000',
        'Days Remaining': '365',
        'Total Claims': '5',
    }
];


export const rawTab3 = [
    {
        'Plan Details': 'Starter Plan',
        'Interest Rate': '6.5%',
        'Amount Invested': '₹2,000',
        'Days Remaining': '0',
        'Total Claims': '1',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Silver Plan',
        'Interest Rate': '7.2%',
        'Amount Invested': '₹5,000',
        'Days Remaining': '0',
        'Total Claims': '2',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Gold Plan',
        'Interest Rate': '8%',
        'Amount Invested': '₹10,000',
        'Days Remaining': '0',
        'Total Claims': '3',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Platinum Plan',
        'Interest Rate': '8.5%',
        'Amount Invested': '₹15,000',
        'Days Remaining': '0',
        'Total Claims': '4',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Diamond Plan',
        'Interest Rate': '9%',
        'Amount Invested': '₹20,000',
        'Days Remaining': '0',
        'Total Claims': '5',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Elite Plan',
        'Interest Rate': '9.5%',
        'Amount Invested': '₹25,000',
        'Days Remaining': '0',
        'Total Claims': '6',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Pro Plan',
        'Interest Rate': '10%',
        'Amount Invested': '₹30,000',
        'Days Remaining': '0',
        'Total Claims': '7',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Investor Plan',
        'Interest Rate': '10.5%',
        'Amount Invested': '₹35,000',
        'Days Remaining': '0',
        'Total Claims': '8',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Max Plan',
        'Interest Rate': '11%',
        'Amount Invested': '₹40,000',
        'Days Remaining': '0',
        'Total Claims': '9',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
    {
        'Plan Details': 'Ultimate Plan',
        'Interest Rate': '11.5%',
        'Amount Invested': '₹50,000',
        'Days Remaining': '0',
        'Total Claims': '10',
        'Status': 'Inactive',
        'Action': 'Withdrawals',
    },
];


export const treeTableData = [
    {
        'Joinee Name': 'Amit Sharma',
        'Referral Code': '2hd6hpfsdee4j4hp569bryryw',
        'Current Staking': '₹5,000',
        'Current Level': 'Level 2',
        'Referred By': 'Suman Das',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Priya Verma',
        'Referral Code': '5jk2weq7h9dfg7s4kfjw7g82sj',
        'Current Staking': '₹8,500',
        'Current Level': 'Level 3',
        'Referred By': 'Amit Sharma',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Rohit Sen',
        'Referral Code': '6ghe2js9kd8q4jhd83hdjks8f2',
        'Current Staking': '₹2,000',
        'Current Level': 'Level 1',
        'Referred By': 'Priya Verma',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Sneha Kapoor',
        'Referral Code': '9sd7f2hd93hd9wfh8sdfh2h4gw',
        'Current Staking': '₹12,000',
        'Current Level': 'Level 4',
        'Referred By': 'Amit Sharma',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Kunal Bhatt',
        'Referral Code': '2ui9hd823jf9sjfd8w3fd9hf3j',
        'Current Staking': '₹6,000',
        'Current Level': 'Level 2',
        'Referred By': 'Rohit Sen',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Megha Tiwari',
        'Referral Code': '8we9d7f2shf8shjfs8hjf9284j',
        'Current Staking': '₹4,000',
        'Current Level': 'Level 1',
        'Referred By': 'Sneha Kapoor',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Anil Kumar',
        'Referral Code': '2hd6hp2hd6hpfsdee4j4hp569b',
        'Current Staking': '₹9,000',
        'Current Level': 'Level 3',
        'Referred By': 'Priya Verma',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Ritika Mehra',
        'Referral Code': 'uhd2wh3d8h23fh2d8fhw9efh9e',
        'Current Staking': '₹11,500',
        'Current Level': 'Level 4',
        'Referred By': 'Amit Sharma',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Deepak Rao',
        'Referral Code': 'fhsdhf8723fh23h8f2hf78sd3f',
        'Current Staking': '₹7,500',
        'Current Level': 'Level 2',
        'Referred By': 'Kunal Bhatt',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Nikita Jain',
        'Referral Code': '6sd7fhd2f8h2f8h27f8w3dhfd9',
        'Current Staking': '₹3,000',
        'Current Level': 'Level 1',
        'Referred By': 'Megha Tiwari',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Yashpal Singh',
        'Referral Code': '3hd9fh23hf8923fh892fh23fh2',
        'Current Staking': '₹15,000',
        'Current Level': 'Level 5',
        'Referred By': 'Anil Kumar',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Pooja Chauhan',
        'Referral Code': '5sd8fhsdhfh23f78hf923f87hf',
        'Current Staking': '₹2,500',
        'Current Level': 'Level 1',
        'Referred By': 'Ritika Mehra',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Aditya Joshi',
        'Referral Code': 'shf23fh7fhs8dhfs9h8f3hf2jf',
        'Current Staking': '₹6,800',
        'Current Level': 'Level 2',
        'Referred By': 'Deepak Rao',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Shivani Desai',
        'Referral Code': 'dfh2df8723fh2f8723fh98wh2f',
        'Current Staking': '₹10,000',
        'Current Level': 'Level 3',
        'Referred By': 'Nikita Jain',
        'Action': 'View More',
    },
    {
        'Joinee Name': 'Harsh Vardhan',
        'Referral Code': 'h3f9h8f2hf2hf2h3f9f2hf9whf',
        'Current Staking': '₹13,500',
        'Current Level': 'Level 4',
        'Referred By': 'Yashpal Singh',
        'Action': 'View More',
    },
];

export const withdrawalsHistoryData = [
    {
        'Matching Rewards': '120 USDT',
        'Level Rewards': '50 USDT',
        'Staking Rewards': '30 USDT',
        'Amount': '200 USDT',
        'Wallet Address': '0xAbc123...7890',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '100 USDT',
        'Level Rewards': '40 USDT',
        'Staking Rewards': '25 USDT',
        'Amount': '165 USDT',
        'Wallet Address': '0xDef456...1234',
        'Status': 'Pending'
    },
    {
        'Matching Rewards': '90 USDT',
        'Level Rewards': '30 USDT',
        'Staking Rewards': '20 USDT',
        'Amount': '140 USDT',
        'Wallet Address': '0xGhi789...5678',
        'Status': 'In Progress'
    },
    {
        'Matching Rewards': '150 USDT',
        'Level Rewards': '60 USDT',
        'Staking Rewards': '35 USDT',
        'Amount': '245 USDT',
        'Wallet Address': '0xJkl012...3456',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '80 USDT',
        'Level Rewards': '25 USDT',
        'Staking Rewards': '15 USDT',
        'Amount': '120 USDT',
        'Wallet Address': '0xMno345...7890',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '110 USDT',
        'Level Rewards': '55 USDT',
        'Staking Rewards': '22 USDT',
        'Amount': '187 USDT',
        'Wallet Address': '0xPqr678...9012',
        'Status': 'Pending'
    },
    {
        'Matching Rewards': '95 USDT',
        'Level Rewards': '45 USDT',
        'Staking Rewards': '20 USDT',
        'Amount': '160 USDT',
        'Wallet Address': '0xStu901...2345',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '105 USDT',
        'Level Rewards': '35 USDT',
        'Staking Rewards': '25 USDT',
        'Amount': '165 USDT',
        'Wallet Address': '0xVwx234...5678',
        'Status': 'In Progress'
    },
    {
        'Matching Rewards': '125 USDT',
        'Level Rewards': '65 USDT',
        'Staking Rewards': '30 USDT',
        'Amount': '220 USDT',
        'Wallet Address': '0xYza567...8901',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '115 USDT',
        'Level Rewards': '50 USDT',
        'Staking Rewards': '28 USDT',
        'Amount': '193 USDT',
        'Wallet Address': '0xBcd890...2345',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '88 USDT',
        'Level Rewards': '33 USDT',
        'Staking Rewards': '19 USDT',
        'Amount': '140 USDT',
        'Wallet Address': '0xCde123...5678',
        'Status': 'Pending'
    },
    {
        'Matching Rewards': '130 USDT',
        'Level Rewards': '70 USDT',
        'Staking Rewards': '40 USDT',
        'Amount': '240 USDT',
        'Wallet Address': '0xEfg456...7890',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '102 USDT',
        'Level Rewards': '48 USDT',
        'Staking Rewards': '26 USDT',
        'Amount': '176 USDT',
        'Wallet Address': '0xFgh789...0123',
        'Status': 'In Progress'
    },
    {
        'Matching Rewards': '97 USDT',
        'Level Rewards': '37 USDT',
        'Staking Rewards': '21 USDT',
        'Amount': '155 USDT',
        'Wallet Address': '0xHij012...3456',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '140 USDT',
        'Level Rewards': '75 USDT',
        'Staking Rewards': '32 USDT',
        'Amount': '247 USDT',
        'Wallet Address': '0xIjk345...6789',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '90 USDT',
        'Level Rewards': '35 USDT',
        'Staking Rewards': '20 USDT',
        'Amount': '145 USDT',
        'Wallet Address': '0xJkl678...9012',
        'Status': 'Pending'
    },
    {
        'Matching Rewards': '108 USDT',
        'Level Rewards': '38 USDT',
        'Staking Rewards': '24 USDT',
        'Amount': '170 USDT',
        'Wallet Address': '0xKlm901...2345',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '112 USDT',
        'Level Rewards': '44 USDT',
        'Staking Rewards': '27 USDT',
        'Amount': '183 USDT',
        'Wallet Address': '0xLmn234...5678',
        'Status': 'Claimed'
    },
    {
        'Matching Rewards': '85 USDT',
        'Level Rewards': '30 USDT',
        'Staking Rewards': '18 USDT',
        'Amount': '133 USDT',
        'Wallet Address': '0xMno567...8901',
        'Status': 'In Progress'
    },
    {
        'Matching Rewards': '118 USDT',
        'Level Rewards': '58 USDT',
        'Staking Rewards': '29 USDT',
        'Amount': '205 USDT',
        'Wallet Address': '0xNop890...1234',
        'Status': 'Claimed'
    }
];
